---
#title: "Untitled"
#author: "Darryl Beatty"
#date: "9 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r library}
library (dplyr)
library(knitr)
library(rmarkdown)
library(kableExtra)
```

```{css}


/* reduce size of tables */
  
.table-condensed>thead>tr>th, .table-condensed>tbody>tr>th, 
.table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, 
.table-condensed>tbody>tr>td, .table-condensed>tfoot>tr>td{
    padding: 1px;
}

.panel-primary>.panel-heading {
color: #fff !important;
background-color: #337ab7 !important;
border-color: #337ab7;
}

.label {
display: inline;
padding: .2em .6em .3em;
font-size: 75%;
font-weight: 700;
line-height: 1;
color: #fff !important;
text-align: center;
white-space: nowrap;
vertical-align: baseline;
border-radius: .25em;
}


.label-primary {
    background-color: #337ab7 !important;
    border-color: #337ab7 !important;
}

.label-warning {
    background-color: #f0ad4e !important;
    border-color: #f0ad4e !important;   
}

.label-success {
    background-color: #5cb85c !important;
    border-color: #5cb85c !important;
}

/*
  https://stackoverflow.com/questions/21032137/sticking-custom-footer-on-each-page-to-bottom-while-printing
*/

@media print{
    .footer{
       position:relative;
       top:-30px; 
       border-top: 1px solid grey;
       height:10px;
    }
  
      .header{
       position:relative;
       top:20px; 
       border-bottom: 1px solid grey;
       height:10px;
    }
}

@media print {
   .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12 {
        float: left;
   }
   .col-sm-12 {
        width: 100%;
   }
   .col-sm-11 {
        width: 91.66666667%;
   }
   .col-sm-10 {
        width: 83.33333333%;
   }
   .col-sm-9 {
        width: 75%;
   }
   .col-sm-8 {
        width: 66.66666667%;
   }
   .col-sm-7 {
        width: 58.33333333%;
   }
   .col-sm-6 {
        width: 50%;
   }
   .col-sm-5 {
        width: 41.66666667%;
   }
   .col-sm-4 {
        width: 33.33333333%;
   }
   .col-sm-3 {
        width: 25%;
   }
   .col-sm-2 {
        width: 16.66666667%;
   }
   .col-sm-1 {
        width: 8.33333333%;
   }
}

```

<!-- # Heading and a label -->
<div class="row" >
<div class="col-sm-10" style="min-height: 80px; max-height: 80px;">
## Table Example
</div>
<div class="col-sm-2" style="min-height: 80px; max-height: 80px;">
<p>&nbsp;</p>
<h4><span class="label label-primary"> `r paste0("Date: ",median(iris$Sepal.Length))`</span></h4> 
</div>
</div>

This is an example of formatting a table using Kable and KableExtra. I have reduced the size of the font, and collapsed column 1.  The table is enclosed in a Blue Bootstrap panel (for a bit of colour). 

<div class="panel panel-primary">
<div class="panel-heading">Star Wars Tables</div>
<div class="panel-body">
```{r}
 starwars%>%
  group_by(gender,species) %>%
  summarise( median.height = median(height),
             median.mass = median(mass)) %>%
  ungroup() %>%
  #mutate (median.height2 = cell_spec( median.height , color = ifelse( median.height  > 206, "red", "blue"))) %>%
  kable(escape = F) %>%
  kable_styling(bootstrap_options = "condensed", font_size = 10) %>%
  collapse_rows(columns = 1, valign = "top")   

```
</div>
</div>


  
  

